# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screenshot.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import time
import pyautogui
import os
from PIL import ImageGrab, ImageQt
import re
import copy
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QThread, QApplication, QMainWindow
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QGraphicsScene, QGraphicsPixmapItem, QFileDialog


class GetPos(QThread):

    def __init__(self, mainwindow):
        super().__init__()
        self.mainwindow = mainwindow

    def run(self):
        while True:
            time.sleep(1)
            x, y = pyautogui.position()
            self.mainwindow.current_pos.setText("x:{} y:{}".format(x,y))



class Ui_MainWindow():

    def setupUi(self, MainWindow):
        self.thread_status = False
        self.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left_up_pos_text = QtWidgets.QLabel(self.centralwidget)
        self.left_up_pos_text.setGeometry(QtCore.QRect(20, 100, 81, 16))
        self.left_up_pos_text.setObjectName("left_up_pos_text")
        self.right_down_pos_text = QtWidgets.QLabel(self.centralwidget)
        self.right_down_pos_text.setGeometry(QtCore.QRect(20, 150, 81, 16))
        self.right_down_pos_text.setObjectName("right_down_pos_text")
        self.enter = QtWidgets.QPushButton(self.centralwidget)
        self.enter.setGeometry(QtCore.QRect(10, 210, 93, 28))
        self.enter.setObjectName("enter")
        self.enter.clicked.connect(self.screenshot)
        self.screenshot_view = QtWidgets.QLabel(self.centralwidget)
        self.screenshot_view.setGeometry(QtCore.QRect(500, 180, 81, 16))
        self.screenshot_view.setObjectName("screenshot_view")
        self.graphicsView = QtWidgets.QLabel(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(380, 230, 401, 311))
        self.graphicsView.setObjectName("pic_view")
        self.tips = QtWidgets.QTextBrowser(self.centralwidget)
        self.tips.setGeometry(QtCore.QRect(0, 350, 256, 192))
        self.tips.setObjectName("tips")
        self.current_pos = QtWidgets.QLabel(self.centralwidget)
        self.current_pos.setGeometry(QtCore.QRect(140, 54, 81, 21))
        self.current_pos.setObjectName("current_pos")
        self.left_up_pos = QtWidgets.QLabel(self.centralwidget)
        self.left_up_pos.setGeometry(QtCore.QRect(140, 100, 91, 16))
        self.left_up_pos.setObjectName("left_up_pos")
        self.right_down_pos = QtWidgets.QLabel(self.centralwidget)
        self.right_down_pos.setGeometry(QtCore.QRect(140, 150, 91, 16))
        self.right_down_pos.setObjectName("right_down_pos")
        self.current_pos_text = QtWidgets.QPushButton(self.centralwidget)
        self.current_pos_text.setGeometry(QtCore.QRect(10, 50, 101, 28))
        self.current_pos_text.setObjectName("current_pos_text")
        self.current_pos_text.clicked.connect(self.get_pos)
        self.enter_2 = QtWidgets.QPushButton(self.centralwidget)
        self.enter_2.setGeometry(QtCore.QRect(130, 210, 93, 28))
        self.enter_2.setObjectName("enter_2")
        self.enter_2.clicked.connect(self.save_pic)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_up_pos_text.setText(_translate("MainWindow", "左上角坐标"))
        self.right_down_pos_text.setText(_translate("MainWindow", "右下角坐标"))
        self.enter.setText(_translate("MainWindow", "截图"))
        self.tips.setHtml(_translate("MainWindow",
                                     "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                     "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                     "p, li { white-space: pre-wrap; }\n"
                                     "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                     "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">按m键标记左上角坐标</p>\n"
                                     "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">按n键标记右下角坐标</p></body></html>"))
        self.current_pos.setText(_translate("MainWindow", "x:0  y:0"))
        self.left_up_pos.setText(_translate("MainWindow", "x:0  y:0"))
        self.right_down_pos.setText(_translate("MainWindow", "x:0  y:0"))
        self.current_pos_text.setText(_translate("MainWindow", "显示当前坐标"))
        self.enter_2.setText(_translate("MainWindow", "保存截图"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.screenshot_view.setText(_translate("MainWindow", "截图预览"))

    def get_pos(self):
        if self.thread_status is False:
            self.thread = GetPos(self)
            self.thread.start()
            self.current_pos_text.setText("停止显示")
            self.thread_status = True
        else:
            self.thread.terminate()
            self.current_pos_text.setText("显示当前坐标")
            self.thread_status = False

    def screenshot(self):
        pattern = "x:(\d+) y:(\d+)"
        l_x_y = self.left_up_pos.text()
        lx,ly = re.findall(pattern, l_x_y)[0]
        r_x_y = self.right_down_pos.text()
        rx, ry = re.findall(pattern, r_x_y)[0]
        img = ImageGrab.grab().crop([int(lx),int(ly),int(rx),int(ry)])
        self.img = img.copy()
        img = ImageQt.ImageQt(img)
        frame = QImage(img)
        # pix = QPixmap.fromImage(frame)
        # self.item = QGraphicsPixmapItem(pix)
        # self.scene = QGraphicsScene()
        # self.scene.addItem(self.item)
        # self.graphicsView.setScene(self.scene)
        # # self.graphicsView.fitInView(self.item)
        # hr_pic = QtGui.QPixmap(imgName).scaled(self.graphicsView.width(), self.graphicsView.height())
        pic = QtGui.QPixmap(frame)
        self.graphicsView.setPixmap(pic)

    def save_pic(self):
        dst = os.environ.get("HOMEPATH")
        filename,type = QFileDialog.getSaveFileName(self,'save file',dst,"PNG (*.png)")
        self.img.save(filename)

class MainWindow(QMainWindow, Ui_MainWindow):

    def __init__(self, parent=None):
        QMainWindow.__init__(self, parent=parent)
        self.setupUi(self)


    def keyPressEvent(self, event):
        print("按了", event.text())
        if event.key() == QtCore.Qt.Key_M:
            x, y = pyautogui.position()
            self.left_up_pos.setText("x:{} y:{}".format(x,y))
        elif event.key() == QtCore.Qt.Key_N:
            x, y = pyautogui.position()
            self.right_down_pos.setText("x:{} y:{}".format(x,y))





if __name__ == "__main__":
    app = QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec())
